### ISSUE TITLE
Missing some Scintilla Messages?

### ISSUE THREAD

**Issue by vinsworldcom** [pryrt/Win32-Mechanize-NotepadPlusPlus#29]
Latest Win32::Mechanize::NotepadPlusPlus 0.002, hence forth referred to as "PerlScript".

I tried the following Scintilla messages which seem to work in NppExec, but not in "PerlScript":

SCI_MULTIPLESELECTADDNEXT
SCI_MULTIPLESELECTADDEACH

Highlight a word in an open editor that has multiple occurrences in the document.
**NppExec:**
```
SCI_SENDMSG SCI_MULTIPLESELECTADDNEXT
```

The next instance of the word is added to the highlighting (multiple selections).

Now, reset, highlight only the first occurrence again:
**"PerlScript"**
```
editor->multipleSelectAddNext();
no message id sent at C:\Users\vinsworldcom\perl5\lib\perl5/Win32/Mechanize/NotepadPlusPlus/Editor.pm line 10895.
```

Inspecting the %SCIMSG hash, those messages don't seem to be present:

```
npp> for (sort(keys (%SCIMSG))) {
More? if (($_ =~ /SELECT/) and ($_ =~ /MULTIPLE/)) {print "$_\n"}}
SCI_GETMULTIPLESELECTION
SCI_SETMULTIPLESELECTION
```

Cheers.

**Comment by pryrt** [comment]
Those messages weren't in the copy of Scintilla.h I got from Notepad++ source code ([in my src/ directory](https://github.com/pryrt/Win32-Mechanize-NotepadPlusPlus/blob/master/src/Scintilla.h))... but is [in the NPP codebase now](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/include/Scintilla.h#L958).  Which means that somehow, my Makefile target which was supposed to download the `Scintilla.h` _didn't_ update it the last time I ran it, not that long before the v0.002 release.  I'll have to look into that.

**Comment by vinsworldcom** [comment]
I believe those messages came in with Notepad++ latest Scintilla update to
version 4.something. So yeah a new scintilla.h is "required".

No worries, whenever you get to it.!

Cheers.

**Comment by pryrt** [comment]
Confirmed the flaw in my makefile targets (the downloads were commented out, but there was a logic bug that would have made those targets not be run anyway, even when I thought they were); created a new target to download those.  It's not fully automatic (doesn't happen every time), but at least when I think I'm forcing the download, it really will. :-)

Working on bringing the new messages and enum keys/values into the module

**Comment by pryrt** [comment]
Michael, could you grab from [branch "bugfix29-missingMessages"](/pryrt/Win32-Mechanize-NotepadPlusPlus/tree/bugfix29-missingMessages) and see if it works for you?

When I tried your experiment, it seems to work for me now

**edit**: Attached tarball: 
[Win32-Mechanize-NotepadPlusPlus-0.002003-rc1.tar.gz](https://github.com/pryrt/Win32-Mechanize-NotepadPlusPlus/files/4434915/Win32-Mechanize-NotepadPlusPlus-0.002003-rc1.tar.gz)

**Comment by vinsworldcom** [comment]
The attached tarball works!  Thanks!  You can close this if you're satisfied with the fix .. I am.
