### ISSUE TITLE
Notepad++ debug info screen pop

### ISSUE THREAD

**Issue by vinsworldcom** [pryrt/Win32-Mechanize-NotepadPlusPlus#82]
Using version 0.008 of "PerlScript"

Notepad++ v8.1.5   (64-bit)
Build time : Oct  5 2021 - 00:45:54
Path : C:\usr\bin\npp64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1237
Current ANSI codepage : 1252
Plugins : 

When I run a "perlscript", I see the Notepad++ debug info window appear and quickly disappear before each script executes.  I thought this was only on startup, but it seems to happen every time I run a "perlscript".  I think it's from the:

`use Win32::Mechanize::NotepadPlusPlus ':all';`

line at the top of all my scripts.

Certainly coming from:

Win32::Mechanize::NotepadPlusPlus::Notepad->_new();

or line 177 in Win32\Mechanize\NotepadPlusPlus\Notepad.pm:
```
    $self->{debugInfo} = $self->_initDebugInfo();
```

Cheers.

**Comment by pryrt** [comment]
Hmm, yeah, I hadn't thought about that implication.

I will look into delaying that initialization until the user first requests debugInfo, rather than during the main initialization

**Comment by pryrt** [comment]
I think I've got a fix committed into main now.  If you want to grab a copy of https://github.com/pryrt/Win32-Mechanize-NotepadPlusPlus/blob/main/lib/Win32/Mechanize/NotepadPlusPlus/Notepad.pm and try it.

But when I try a `perl -MWin32::Mechanize::NotepadPlusPlus=:all -e 1` , it no longer pops up the Debug Info every run, but if you run a getDebugInfo() , it will do a just-in-time grab of the data, and it still passes all the same test suite (when you do that call, it will do a single popup).  I'll update the documentation to indicate that users should expect a quick popup of the dialog the first time in a script that they access this method.

**Comment by vinsworldcom** [comment]
Seems to work for me too - I no longer see the pop-up of Debug unless i call the notepad->getDebugInfo() .

Quick work!!

Cheers.

**Comment by pryrt** [comment]
closed by [fba57e2](https://github.com/pryrt/Win32-Mechanize-NotepadPlusPlus/commit/fba57e246f79f899205143f35f782bc610457468)  and released in https://github.com/pryrt/Win32-Mechanize-NotepadPlusPlus/commit/67a333a530cd20610aa79d2cb14078e37168ca34
